vendor: China Mobile Information Technology Company Limited
name: China Mobile CMIT PaaS
version: V2022.03
website_url: https://www.chinamobileltd.com/en/global/home.php
documentation_url: https://renyijun-dev.github.io/PaasIntroduction/demo.html
product_logo_url: https://landscape.cncf.io/logos/china-mobile-cmit-paa-s.svg
type: distribution
description: 'Cmit PaaS platform provide core services such as flexible cluster expansion and contraction, disaster tolerance and DevOps.'
contact_email_address: yinxingyu@chinamobile.com
